/**
 * This file was created using the `createProject` gradle task (./gradlew createProject)
 *
 * Please use the task when creating a new project, rather than copying an existing project and
 * modifying its settings.
 */

import androidx.build.SoftwareType
import androidx.build.PlatformIdentifier

plugins {
    id("AndroidXPlugin")
    id("JetBrainsAndroidXPlugin")
    alias(libs.plugins.kotlinSerialization)
}
androidXMultiplatform {
    redirect("androidx.savedstate") {
        androidLibrary {
            namespace = "org.jetbrains.savedstate.compose"
        }
        desktop()
        mingwX64()
        linux()
        macosArm64()
        ios()
        tvos()
        watchos()
        js()
        wasmJs()
    }

    // Build the missing Intel macOS variant from the current sources.
    macosX64()

    defaultPlatform(PlatformIdentifier.ANDROID)

    sourceSets {
        // jbVerifyForkDependencies: suppress
        commonMain {
            dependencies {
                api(project(":savedstate:savedstate"))
                api(project(":compose:runtime:runtime"))
            }
        }

        create("nonAndroidMain").dependsOn(commonMain)
        desktopMain.dependsOn(nonAndroidMain)
        nonJvmMain.dependsOn(nonAndroidMain)
    }
}

androidx {
    name = "Saved State Compose"
    type = SoftwareType.PUBLISHED_LIBRARY
    inceptionYear = "2024"
    description = "Compose integration with Saved State"
}
